// apps/main/frontend/src/app/features/admin-permissions/user-roles-dialog.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  linkedSignal,
  output,
} from '@angular/core';
import { DialogPanelComponent, BadgeComponent, ButtonDirective } from '@aspect/ui';
import { AuthStore } from '../../shared/auth/auth.store';
import type { KeycloakRole, KeycloakUser } from './admin-permissions.types';

const PROTECTED_ROLES = new Set(['admin', 'role_manager']);

@Component({
  selector: 'app-user-roles-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DialogPanelComponent, BadgeComponent, ButtonDirective],
  template: `
    <ui-dialog-panel (closed)="closed.emit()">
      <span dialogTitle>Manage Roles for {{ user().username }}</span>
      <div class="flex flex-col gap-sm">
        @for (role of allRoles(); track role.name) {
          <label class="flex items-center gap-sm">
            <input
              type="checkbox"
              [checked]="selectedRoles().has(role.name)"
              (change)="onToggle(role.name, $event)"
              [disabled]="isProtectedForCurrentUser(role.name)"
            />
            <span>{{ role.name }}</span>
            @if (isProtected(role.name)) {
              <ui-badge [variant]="'secondary'">protected</ui-badge>
            }
          </label>
        }
      </div>
      <ng-container dialogFooter>
        <button uiButton [variant]="'outline'" (click)="closed.emit()">Close</button>
        <button uiButton (click)="onSave()" [disabled]="!hasChanges()">Save Changes</button>
      </ng-container>
    </ui-dialog-panel>
  `,
})
export class UserRolesDialogComponent {
  readonly user = input.required<KeycloakUser>();
  readonly allRoles = input.required<KeycloakRole[]>();
  readonly closed = output();
  readonly rolesChanged = output<{ added: string[]; removed: string[] }>();

  private readonly auth = inject(AuthStore);
  private readonly currentUserIsAdmin = computed(
    () => this.auth.user()?.roles.includes('admin') ?? false,
  );

  protected readonly selectedRoles = linkedSignal<KeycloakUser, Set<string>>({
    source: this.user,
    computation: (user) => new Set(user.roles),
  });

  protected readonly hasChanges = computed(() => {
    const original = new Set(this.user().roles);
    const current = this.selectedRoles();
    if (original.size !== current.size) return true;
    for (const r of current) {
      if (!original.has(r)) return true;
    }
    return false;
  });

  protected isProtected(roleName: string): boolean {
    return PROTECTED_ROLES.has(roleName);
  }

  protected isProtectedForCurrentUser(roleName: string): boolean {
    return this.isProtected(roleName) && !this.currentUserIsAdmin();
  }

  protected onToggle(roleName: string, event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    const updated = new Set(this.selectedRoles());
    if (checked) {
      updated.add(roleName);
    } else {
      updated.delete(roleName);
    }
    this.selectedRoles.set(updated);
  }

  protected onSave(): void {
    const original = new Set(this.user().roles);
    const current = this.selectedRoles();
    const added = [...current].filter((r) => !original.has(r));
    const removed = [...original].filter((r) => !current.has(r));
    this.rolesChanged.emit({ added, removed });
  }
}

// apps/main/react-frontend/src/features/admin/user-roles-dialog.tsx
import { useState, useMemo } from 'react';
import { DialogPanel, Badge, Button } from '@aspect/react-ui';
import { useAuth } from '../../core/auth-context';
import type { KeycloakUser, KeycloakRole } from '../../core/api.types';

const PROTECTED_ROLES = new Set(['admin', 'role_manager']);

interface Props {
  user: KeycloakUser;
  allRoles: KeycloakRole[];
  onClose: () => void;
  onSave: (added: string[], removed: string[]) => void;
}

export function UserRolesDialog({ user, allRoles, onClose, onSave }: Props) {
  const { user: authUser } = useAuth();
  const isAdmin = authUser?.roles.includes('admin') ?? false;

  const originalRoles = useMemo(
    () => new Set(user.roles.map((r) => r.name)),
    [user],
  );
  const [selected, setSelected] = useState(() => new Set(originalRoles));

  const hasChanges = useMemo(() => {
    if (selected.size !== originalRoles.size) return true;
    for (const r of selected) if (!originalRoles.has(r)) return true;
    return false;
  }, [selected, originalRoles]);

  const toggle = (name: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(name)) next.delete(name);
      else next.add(name);
      return next;
    });
  };

  const handleSave = () => {
    const added = [...selected].filter((r) => !originalRoles.has(r));
    const removed = [...originalRoles].filter((r) => !selected.has(r));
    onSave(added, removed);
  };

  return (
    <DialogPanel
      title={<span>Roles for {user.username}</span>}
      onClose={onClose}
      footer={
        <div className="flex gap-sm justify-end">
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSave} disabled={!hasChanges}>Save</Button>
        </div>
      }
    >
      <div className="flex flex-col gap-sm">
        {allRoles.map((role) => {
          const isProtected = PROTECTED_ROLES.has(role.name);
          return (
            <label key={role.name} className="flex items-center gap-sm">
              <input
                type="checkbox"
                checked={selected.has(role.name)}
                onChange={() => toggle(role.name)}
                disabled={isProtected && !isAdmin}
              />
              <span>{role.name}</span>
              {isProtected && <Badge variant="secondary">protected</Badge>}
            </label>
          );
        })}
      </div>
    </DialogPanel>
  );
}
