// apps/main/frontend/src/app/features/admin-permissions/users-tab.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import {
  DataTableComponent,
  DataTableColumnComponent,
  BadgeComponent,
  InputComponent,
} from '@aspect/ui';
import { UsersTabStore } from './users-tab.store';
import { UserRolesDialogComponent } from './user-roles-dialog.component';
import { RolesManagementComponent } from './roles-management.component';
import type { KeycloakUser } from './admin-permissions.types';

@Component({
  selector: 'app-users-tab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [UsersTabStore],
  imports: [
    DataTableComponent,
    DataTableColumnComponent,
    BadgeComponent,
    InputComponent,
    UserRolesDialogComponent,
    RolesManagementComponent,
  ],
  template: `
    <div class="flex justify-between items-center mb-md">
      <h2 class="text-lg font-semibold">User Management</h2>
      <ui-input placeholder="Search users..." (valueChange)="onSearch($event)" />
    </div>

    @if (store.loading()) {
      <p>Loading...</p>
    } @else if (store.error(); as error) {
      <p class="text-destructive">{{ error }}</p>
    } @else {
      <ui-data-table
        [dataSource]="store.users()"
        [clickableRows]="true"
        (rowClick)="onSelectUser($event)"
      >
        <ui-data-table-column columnDef="username" label="Username" [sortable]="true" />
        <ui-data-table-column columnDef="email" label="Email" [sortable]="true" />
        <ui-data-table-column columnDef="enabled" label="Status">
          <ng-template #cell let-row>
            <ui-badge [variant]="row.enabled ? 'default' : 'destructive'">
              {{ row.enabled ? 'Active' : 'Disabled' }}
            </ui-badge>
          </ng-template>
        </ui-data-table-column>
        <ui-data-table-column columnDef="roles" label="Roles">
          <ng-template #cell let-row>
            @for (role of row.roles; track role) {
              <ui-badge [variant]="'outline'" class="mr-xs">{{ role }}</ui-badge>
            }
          </ng-template>
        </ui-data-table-column>
      </ui-data-table>
    }

    <div class="mt-lg">
      <app-roles-management />
    </div>

    @if (selectedUser()) {
      <app-user-roles-dialog
        [user]="selectedUser()!"
        [allRoles]="store.allRoles()"
        (closed)="selectedUser.set(null)"
        (rolesChanged)="onRolesChanged($event)"
      />
    }
  `,
})
export class UsersTabComponent implements OnInit {
  protected readonly store = inject(UsersTabStore);
  protected readonly selectedUser = signal<KeycloakUser | null>(null);

  ngOnInit(): void {
    void this.store.loadUsers();
    void this.store.loadRoles();
  }

  protected onSearch(value: string): void {
    void this.store.loadUsers(value || undefined);
  }

  protected onSelectUser(user: KeycloakUser): void {
    this.selectedUser.set(user);
  }

  protected async onRolesChanged(changes: {
    added: string[];
    removed: string[];
  }): Promise<void> {
    const user = this.selectedUser();
    if (!user) return;
    if (changes.added.length > 0) {
      await this.store.assignRoles(user.id, changes.added);
    }
    if (changes.removed.length > 0) {
      await this.store.removeRoles(user.id, changes.removed);
    }
    this.selectedUser.set(null);
  }
}

// apps/main/react-frontend/src/features/admin/users-tab.tsx
import { useCallback, useEffect, useState } from 'react';
import { Badge, Button, DataTable, Input, type DataTableColumn } from '@aspect/react-ui';
import { api } from '../../core/api';
import type { KeycloakUser, KeycloakRole } from '../../core/api.types';
import { UserRolesDialog } from './user-roles-dialog';
import { RolesManagement } from './roles-management';

export default function UsersTab() {
  const [users, setUsers] = useState<KeycloakUser[]>([]);
  const [allRoles, setAllRoles] = useState<KeycloakRole[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedUser, setSelectedUser] = useState<KeycloakUser | null>(null);

  const loadUsers = useCallback(async (q?: string) => {
    setLoading(true);
    try {
      const res = await api.listUsers({ search: q, offset: 0, limit: 50 });
      setUsers(res.items);
    } finally {
      setLoading(false);
    }
  }, []);

  const loadRoles = useCallback(async () => {
    try {
      setAllRoles(await api.listRoles());
    } catch {
      /* non-critical */
    }
  }, []);

  useEffect(() => {
    void loadUsers();
    void loadRoles();
  }, [loadUsers, loadRoles]);

  const handleSearch = (value: string) => {
    setSearch(value);
    void loadUsers(value || undefined);
  };

  const handleRolesChanged = async (added: string[], removed: string[]) => {
    if (!selectedUser) return;
    if (added.length > 0) await api.assignRoles(selectedUser.id, added);
    if (removed.length > 0) await api.removeRoles(selectedUser.id, removed);
    setSelectedUser(null);
    await loadUsers(search || undefined);
  };

  const columns: DataTableColumn<KeycloakUser>[] = [
    { accessor: 'username', header: 'Username' },
    { accessor: 'email', header: 'Email' },
    {
      accessor: 'enabled',
      header: 'Status',
      cell: (row) => (
        <Badge variant={row.enabled ? 'default' : 'destructive'}>
          {row.enabled ? 'Active' : 'Disabled'}
        </Badge>
      ),
    },
    {
      accessor: 'roles' as keyof KeycloakUser & string,
      header: 'Roles',
      cell: (row) => (
        <div className="flex flex-wrap gap-xs">
          {row.roles.map((r) => (
            <Badge
              key={r.name}
              variant={r.name === 'admin' ? 'default' : 'secondary'}
            >
              {r.name}
            </Badge>
          ))}
        </div>
      ),
    },
    {
      accessor: 'id',
      header: '',
      cell: (row) => (
        <Button variant="outline" size="sm" onClick={() => setSelectedUser(row)}>
          Manage
        </Button>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-md">
      <Input
        label="Search users"
        placeholder="Search by username or email"
        value={search}
        onValueChange={handleSearch}
      />
      {loading ? (
        <p className="text-muted-foreground">Loading…</p>
      ) : (
        <DataTable data={users} columns={columns} />
      )}
      <RolesManagement
        roles={allRoles}
        onCreate={async (name, desc) => {
          await api.createRole({ name, description: desc });
          await loadRoles();
        }}
        onDelete={async (name) => {
          await api.deleteRole(name);
          await loadRoles();
        }}
      />
      {selectedUser && (
        <UserRolesDialog
          user={selectedUser}
          allRoles={allRoles}
          onClose={() => setSelectedUser(null)}
          onSave={(added, removed) => void handleRolesChanged(added, removed)}
        />
      )}
    </div>
  );
}
