// apps/main/react-frontend/src/features/admin/permission-form.tsx
import { useState, useEffect, type FormEvent } from 'react';
import { Input, FormError, Button } from '@aspect/react-ui';
import type { PermissionMapping } from '../../core/api.types';

export interface PermissionFormValue {
  role: string;
  route_pattern: string;
  method: string;
  frontend_route: string;
}

interface Props {
  permission?: PermissionMapping | null;
  onSubmit: (value: PermissionFormValue) => void;
  onCancel: () => void;
}

export function PermissionForm({ permission, onSubmit, onCancel }: Props) {
  const [form, setForm] = useState<PermissionFormValue>({
    role: '',
    route_pattern: '',
    method: '',
    frontend_route: '',
  });
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  useEffect(() => {
    if (permission) {
      setForm({
        role: permission.role,
        route_pattern: permission.route_pattern,
        method: permission.method,
        frontend_route: permission.frontend_route ?? '',
      });
    }
  }, [permission]);

  const errors: Record<string, Record<string, true>> = {};
  if (!form.role.trim()) errors.role = { required: true };
  if (!form.route_pattern.trim()) errors.route_pattern = { required: true };
  if (!form.method.trim()) errors.method = { required: true };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    setTouched({ role: true, route_pattern: true, method: true });
    if (Object.keys(errors).length > 0) return;
    onSubmit(form);
  };

  const set = (key: keyof PermissionFormValue) => (v: string) =>
    setForm((f) => ({ ...f, [key]: v }));
  const touch = (key: string) => () =>
    setTouched((t) => ({ ...t, [key]: true }));

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-sm">
      <Input label="Role" value={form.role} onValueChange={set('role')} onBlur={touch('role')} />
      <FormError errors={errors.role} touched={touched.role} />
      <Input label="Route Pattern" value={form.route_pattern} onValueChange={set('route_pattern')} onBlur={touch('route_pattern')} />
      <FormError errors={errors.route_pattern} touched={touched.route_pattern} />
      <Input label="Method" value={form.method} onValueChange={set('method')} onBlur={touch('method')} />
      <FormError errors={errors.method} touched={touched.method} />
      <Input label="Frontend Route" value={form.frontend_route} onValueChange={set('frontend_route')} />
      <div className="flex justify-end gap-sm">
        <Button type="button" variant="outline" onClick={onCancel}>Cancel</Button>
        <Button type="submit">{permission ? 'Update' : 'Create'}</Button>
      </div>
    </form>
  );
}

// apps/main/frontend/src/app/features/admin-permissions/permission-form.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  input,
  output,
} from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { InputComponent, FormErrorComponent, ButtonDirective } from '@aspect/ui';
import type { PermissionMapping } from './admin-permissions.types';

export interface PermissionFormValue {
  role: string;
  route_pattern: string;
  method: string;
  frontend_route: string | null;
}

@Component({
  selector: 'app-permission-form',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, InputComponent, FormErrorComponent, ButtonDirective],
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit()" class="flex flex-col gap-md">
      <ui-input formControlName="role" label="Role" placeholder="e.g. admin" />
      <ui-form-error [control]="form.controls.role" />
      <ui-input
        formControlName="route_pattern"
        label="Route Pattern"
        placeholder="/api/..."
      />
      <ui-form-error [control]="form.controls.route_pattern" />
      <ui-input
        formControlName="method"
        label="HTTP Method"
        placeholder="GET, POST, *, etc."
      />
      <ui-form-error [control]="form.controls.method" />
      <ui-input
        formControlName="frontend_route"
        label="Frontend Route (optional)"
        placeholder="/dashboard"
      />
      <div class="flex gap-sm justify-end">
        <button uiButton [variant]="'outline'" type="button" (click)="cancelled.emit()">
          Cancel
        </button>
        <button uiButton type="submit">Save</button>
      </div>
    </form>
  `,
})
export class PermissionFormComponent {
  readonly permission = input<PermissionMapping | null>(null);
  readonly submitted = output<PermissionFormValue>();
  readonly cancelled = output<void>();

  readonly form = new FormGroup({
    role: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    route_pattern: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required],
    }),
    method: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
    frontend_route: new FormControl('', { nonNullable: true }),
  });

  private readonly _syncForm = effect(() => {
    const perm = this.permission();
    if (perm) {
      this.form.patchValue({
        role: perm.role,
        route_pattern: perm.route_pattern,
        method: perm.method,
        frontend_route: perm.frontend_route ?? '',
      });
    } else {
      this.form.reset();
    }
  });

  protected onSubmit(): void {
    this.form.markAllAsTouched();
    if (this.form.invalid) return;
    const raw = this.form.getRawValue();
    this.submitted.emit({
      ...raw,
      frontend_route: raw.frontend_route || null,
    });
  }
}
