// packages/react-ui/src/data-table-tree-filter.tsx
import { type HTMLAttributes, useCallback, useMemo, useState } from 'react';
import type { FilterPosition } from './data-table-filter.types';
import type {
  TreeFilterNode,
  TreeSelectionChangeEvent,
} from './data-table-tree-filter.types';
import {
  flatten,
  isAncestorExpanded,
  isPathPrefix,
  pathKey,
  selectionState,
  updateSelection,
} from './data-table-tree-filter.utils';

export interface DataTableTreeFilterProps
  extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  filterId: string;
  column: string;
  options: TreeFilterNode[];
  multi?: boolean;
  position?: FilterPosition;
  onSelectionChange?: (event: TreeSelectionChangeEvent) => void;
}

export function DataTableTreeFilter({
  filterId,
  column,
  options,
  multi = false,
  position = 'left',
  onSelectionChange,
  className,
  ...props
}: DataTableTreeFilterProps) {
  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(
    () => new Set(),
  );
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(
    () => new Set(),
  );

  const flatNodes = useMemo(() => flatten(options, []), [options]);

  const visibleNodes = useMemo(() => {
    return flatNodes
      .filter(
        (n) => n.depth === 0 || isAncestorExpanded(n.path, expandedKeys),
      )
      .map((n) => ({
        ...n,
        expanded: expandedKeys.has(pathKey(n.path)),
        ...selectionState(n, selectedKeys, flatNodes),
      }));
  }, [flatNodes, expandedKeys, selectedKeys]);

  const toggleExpand = useCallback((path: string[]) => {
    const key = pathKey(path);
    setExpandedKeys((prev) => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  }, []);

  const toggleSelect = useCallback(
    (path: string[]) => {
      const key = pathKey(path);
      const descendants = flatNodes.filter(
        (n) => n.path.length > path.length && isPathPrefix(path, n.path),
      );
      setSelectedKeys((prev) => {
        const next = updateSelection(prev, key, descendants, multi);
        const paths = flatNodes
          .filter((n) => next.has(pathKey(n.path)))
          .map((n) => n.path);
        onSelectionChange?.({ filterId, selectedPaths: paths });
        return next;
      });
    },
    [flatNodes, multi, filterId, onSelectionChange],
  );

  return (
    <div
      className={
        className
          ? `data-table-filter tree-filter ${className}`
          : 'data-table-filter tree-filter'
      }
      data-position={position}
      data-filter-id={filterId}
      {...props}
    >
      {visibleNodes.map((node) => (
        <div
          key={node.path.join('.')}
          className="tree-filter-node"
          style={{ '--tree-depth': node.depth } as React.CSSProperties}
        >
          {node.expandable ? (
            <button
              className="tree-filter-toggle"
              onClick={() => toggleExpand(node.path)}
              type="button"
            >
              <span
                className={
                  node.expanded
                    ? 'tree-filter-arrow tree-filter-arrow-open'
                    : 'tree-filter-arrow'
                }
              >
                &#9654;
              </span>
            </button>
          ) : (
            <span className="tree-filter-spacer" />
          )}
          {multi ? (
            <input
              type="checkbox"
              checked={node.selected}
              ref={(el) => {
                if (el) el.indeterminate = node.indeterminate;
              }}
              onChange={() => toggleSelect(node.path)}
              className="tree-filter-input"
            />
          ) : (
            <input
              type="radio"
              checked={node.selected}
              name={filterId}
              onChange={() => toggleSelect(node.path)}
              className="tree-filter-input"
            />
          )}
          <span className="tree-filter-label">{node.label}</span>
        </div>
      ))}
    </div>
  );
}

// packages/ui/src/data-table-tree-filter.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  OnInit,
  computed,
  inject,
  input,
  output,
  signal,
} from '@angular/core';

import { DataTableComponent } from './data-table.component';
import type { FilterPosition } from './data-table-filter.types';
import type {
  TreeFilterNode,
  TreeSelectionChangeEvent,
} from './data-table-tree-filter.types';
import {
  filterByPaths,
  flatten,
  isAncestorExpanded,
  isPathPrefix,
  pathKey,
  selectionState,
  updateSelection,
} from './data-table-tree-filter.utils';

@Component({
  selector: 'ui-data-table-tree-filter',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'data-table-filter tree-filter',
    '[attr.data-position]': 'position()',
    '[attr.data-filter-id]': 'filterId()',
  },
  template: `
    @for (node of visibleNodes(); track node.path.join('.')) {
      <div class="tree-filter-node" [style.--tree-depth]="node.depth">
        @if (node.expandable) {
          <button class="tree-filter-toggle"
            (click)="toggleExpand(node.path)" type="button">
            <span [class.tree-filter-arrow-open]="node.expanded"
              class="tree-filter-arrow">&#9654;</span>
          </button>
        } @else {
          <span class="tree-filter-spacer"></span>
        }
        @if (multi()) {
          <input type="checkbox" [checked]="node.selected"
            [indeterminate]="node.indeterminate"
            (click)="toggleSelect(node.path)" class="tree-filter-input" />
        } @else {
          <input type="radio" [checked]="node.selected" [name]="filterId()"
            (click)="toggleSelect(node.path)" class="tree-filter-input" />
        }
        <span class="tree-filter-label">{{ node.label }}</span>
      </div>
    }
  `,
})
export class DataTableTreeFilterComponent<T = Record<string, unknown>>
  implements OnInit
{
  readonly filterId = input.required<string>();
  readonly column = input.required<string>();
  readonly options = input.required<TreeFilterNode[]>();
  readonly multi = input(false);
  readonly position = input<FilterPosition>('left');
  readonly dependsOn = input<string | null>(null);

  readonly selectionChange = output<TreeSelectionChangeEvent>();

  readonly table = inject(DataTableComponent, { optional: false });
  private readonly destroyRef = inject(DestroyRef);

  private readonly expandedKeys = signal(new Set<string>());
  private readonly selectedKeys = signal(new Set<string>());

  readonly flatNodes = computed(() => flatten(this.options(), []));

  readonly visibleNodes = computed(() => {
    const all = this.flatNodes();
    const expanded = this.expandedKeys();
    const selected = this.selectedKeys();
    return all
      .filter((n) => n.depth === 0 || isAncestorExpanded(n.path, expanded))
      .map((n) => ({
        ...n,
        expanded: expanded.has(pathKey(n.path)),
        ...selectionState(n, selected, all),
      }));
  });

  readonly value = computed(() => {
    const sel = this.selectedKeys();
    if (sel.size === 0) return null;
    const all = this.flatNodes();
    return all.filter((n) => sel.has(pathKey(n.path))).map((n) => n.path);
  });

  ngOnInit(): void {
    if (!this.table) {
      throw new Error(
        'ui-data-table-tree-filter must be used inside a ui-data-table',
      );
    }
    this.table.registerFilter(this);
    this.destroyRef.onDestroy(() => this.table.unregisterFilter(this));
  }

  applyFilter(rows: T[]): T[] {
    const paths = this.value();
    if (!paths || paths.length === 0) return rows;
    return filterByPaths(rows, paths, this.column());
  }

  toggleExpand(path: string[]): void {
    const key = pathKey(path);
    this.expandedKeys.update((prev) => {
      const next = new Set(prev);
      next.has(key) ? next.delete(key) : next.add(key);
      return next;
    });
  }

  toggleSelect(path: string[]): void {
    const key = pathKey(path);
    const descendants = this.flatNodes().filter(
      (n) => n.path.length > path.length && isPathPrefix(path, n.path),
    );
    this.selectedKeys.update((prev) =>
      updateSelection(prev, key, descendants, this.multi()),
    );
    this.emitChange();
  }

  private emitChange(): void {
    const paths = this.value();
    this.selectionChange.emit({
      filterId: this.filterId(),
      selectedPaths: paths ?? [],
    });
  }
}
