// packages/react-ui/src/map-popup.tsx
import { type ReactNode, useEffect, useRef } from 'react';
import { Popup } from 'maplibre-gl';
import type { MapCenter, MapPopupAnchor, MapPopupVariant } from './map-view.types';
import { useMapView } from './map-view.context';

export interface MapPopupProps {
  lngLat: MapCenter;
  anchor?: MapPopupAnchor;
  variant?: MapPopupVariant;
  offset?: number;
  closeOnMapClick?: boolean;
  onClose?: () => void;
  children?: ReactNode;
}

export function MapPopup({
  lngLat,
  anchor = 'bottom',
  variant = 'default',
  offset = 12,
  closeOnMapClick = true,
  onClose,
  children,
}: MapPopupProps) {
  const { map } = useMapView();
  const containerRef = useRef<HTMLDivElement>(null);
  const popupRef = useRef<Popup | null>(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  useEffect(() => {
    if (!map || !containerRef.current || popupRef.current) return;

    const popup = new Popup({
      closeButton: false,
      closeOnClick: closeOnMapClick,
      anchor,
      offset,
      className: 'map-popup-container',
    })
      .setDOMContent(containerRef.current)
      .setLngLat([lngLat.lng, lngLat.lat])
      .addTo(map);

    popup.on('close', () => {
      onCloseRef.current?.();
    });

    popupRef.current = popup;

    return () => {
      popup.remove();
      popupRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map]);

  useEffect(() => {
    popupRef.current?.setLngLat([lngLat.lng, lngLat.lat]);
  }, [lngLat.lng, lngLat.lat]);

  return (
    <div ref={containerRef} className="map-popup" data-variant={variant}>
      <div className="map-popup-content">{children}</div>
      {variant !== 'tooltip' && (
        <button
          className="map-popup-close"
          type="button"
          aria-label="Close popup"
          onClick={() => onClose?.()}
        >
          &times;
        </button>
      )}
    </div>
  );
}

// packages/ui/src/map-popup.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  DestroyRef,
  ElementRef,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { Popup } from 'maplibre-gl';
import { MapViewComponent } from './map-view.component';
import type { MapCenter, MapPopupAnchor, MapPopupVariant } from './map-view.types';

@Component({
  selector: 'ui-map-popup',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'map-popup',
    '[attr.data-variant]': 'variant()',
  },
  template: `
    <div class="map-popup-content">
      <ng-content />
    </div>
    @if (variant() !== 'tooltip') {
      <button
        class="map-popup-close"
        type="button"
        aria-label="Close popup"
        (click)="closed.emit()"
      >&times;</button>
    }
  `,
})
export class MapPopupComponent {
  readonly lngLat = input.required<MapCenter>();
  readonly anchor = input<MapPopupAnchor>('bottom');
  readonly variant = input<MapPopupVariant>('default');
  readonly offset = input<number>(12);
  readonly closeOnMapClick = input<boolean>(true);

  readonly closed = output();

  private readonly parent = inject(MapViewComponent);
  private readonly el: HTMLElement = inject(ElementRef).nativeElement as HTMLElement;
  private readonly destroyRef = inject(DestroyRef);
  private readonly popupInstance = signal<Popup | null>(null);

  constructor() {
    effect(() => {
      const map = this.parent.mapInstance();
      if (!map || this.popupInstance()) return;
      this.initPopup(map);
    });

    effect(() => {
      const popup = this.popupInstance();
      if (!popup) return;
      const pos = this.lngLat();
      popup.setLngLat([pos.lng, pos.lat]);
    });

    this.destroyRef.onDestroy(() => {
      this.popupInstance()?.remove();
    });
  }

  private initPopup(map: Parameters<Popup['addTo']>[0]): void {
    const pos = this.lngLat();
    const popup = new Popup({
      closeButton: false,
      closeOnClick: this.closeOnMapClick(),
      anchor: this.anchor(),
      offset: this.offset(),
      className: 'map-popup-container',
    })
      .setDOMContent(this.el)
      .setLngLat([pos.lng, pos.lat])
      .addTo(map);

    popup.on('close', () => {
      this.closed.emit();
    });

    this.popupInstance.set(popup);
  }
}
