// packages/react-ui/src/sidebar-layout.tsx
import { type HTMLAttributes, type ReactNode } from 'react';

export type SidebarSide = 'left' | 'right';

export interface SidebarLayoutProps extends HTMLAttributes<HTMLDivElement> {
  side?: SidebarSide;
  sidebar?: ReactNode;
  children?: ReactNode;
}

export function SidebarLayout({
  side = 'left',
  sidebar,
  className,
  children,
  ...props
}: SidebarLayoutProps) {
  return (
    <div
      className={className ? `sidebar-layout ${className}` : 'sidebar-layout'}
      data-side={side}
      {...props}
    >
      <aside className="sidebar-layout-sidebar">{sidebar}</aside>
      <div className="sidebar-layout-main">{children}</div>
    </div>
  );
}

// packages/ui/src/sidebar-layout.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

export type SidebarSide = 'left' | 'right';

@Component({
  selector: 'ui-sidebar-layout',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'sidebar-layout',
    '[attr.data-side]': 'side()',
  },
  template: `
    <aside class="sidebar-layout-sidebar">
      <ng-content select="[sidebar]" />
    </aside>
    <div class="sidebar-layout-main">
      <ng-content />
    </div>
  `,
})
export class SidebarLayoutComponent {
  readonly side = input<SidebarSide>('left');
}
