// packages/ui/src/dialog-panel.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CdkTrapFocus } from '@angular/cdk/a11y';

@Component({
  selector: 'ui-dialog-panel',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CdkTrapFocus],
  host: {
    '(keydown.escape)': 'closed.emit()',
  },
  template: `
    <div
      class="dialog-backdrop"
      aria-hidden="true"
      (click)="closed.emit()"
    ></div>

    <div
      cdkTrapFocus
      role="dialog"
      aria-modal="true"
      class="dialog-panel"
      [attr.data-variant]="variant()"
    >
      <div class="dialog-title">
        <ng-content select="[dialogTitle]" />
      </div>
      <div class="dialog-body">
        <ng-content />
      </div>
      <div class="dialog-footer">
        <ng-content select="[dialogFooter]" />
      </div>
    </div>
  `,
})
export class DialogPanelComponent {
  readonly variant = input<'default' | 'destructive'>('default');
  readonly closed = output();
}

// packages/react-ui/src/dialog-panel.tsx
import { type ReactNode, useEffect } from 'react';

export interface DialogPanelProps {
  variant?: 'default' | 'destructive';
  onClose?: () => void;
  title?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}

export function DialogPanel({
  variant = 'default',
  onClose,
  title,
  footer,
  children,
}: DialogPanelProps) {
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose?.();
    };
    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [onClose]);

  return (
    <>
      <div
        className="dialog-backdrop"
        onClick={() => onClose?.()}
        aria-hidden="true"
      />
      <div
        className="dialog-panel"
        data-variant={variant}
        role="dialog"
        aria-modal="true"
      >
        {title && <div className="dialog-title">{title}</div>}
        <div className="dialog-body">{children}</div>
        {footer && <div className="dialog-footer">{footer}</div>}
      </div>
    </>
  );
}
