// packages/ui/src/grid.component.ts
import { ChangeDetectionStrategy, Component, computed, Directive, input } from '@angular/core';

export type GridGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

@Component({
  selector: 'ui-grid',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'layout-grid',
    '[attr.data-gap]': 'gap()',
    '[style.--grid-cols]': 'colsVar()',
    '[style.grid-template-columns]': 'colsTemplate()',
    '[style.flex]': 'fill() ? 1 : null',
    '[style.min-height]': 'fill() ? 0 : null',
  },
  template: `<ng-content />`,
})
export class GridComponent {
  readonly cols = input<number | string | undefined>(undefined);
  readonly gap = input<GridGap>('md');
  readonly fill = input(false);

  protected readonly colsVar = computed(() => {
    const c = this.cols();
    return typeof c === 'number' ? c : null;
  });

  protected readonly colsTemplate = computed(() => {
    const c = this.cols();
    return typeof c === 'string' ? c : null;
  });
}

@Directive({
  selector: '[uiCell]',
  host: {
    '[style.grid-column]': 'gridColumn()',
    '[style.grid-column-start]': 'start() ?? null',
    '[style.grid-row]': 'rowSpan() ? "span " + rowSpan() : null',
  },
})
export class CellDirective {
  readonly span = input<number | 'full' | undefined>(undefined);
  readonly start = input<number | undefined>(undefined);
  readonly rowSpan = input<number | undefined>(undefined);

  protected readonly gridColumn = computed(() => {
    const s = this.span();
    if (s === undefined) return null;
    return s === 'full' ? '1 / -1' : `span ${s}`;
  });
}

// packages/react-ui/src/grid.tsx
import {
  type CSSProperties,
  type ElementType,
  type HTMLAttributes,
  type ReactNode,
  createElement,
} from 'react';

export type GridGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export interface GridProps extends HTMLAttributes<HTMLElement> {
  /** Column definition. Number → `repeat(n, 1fr)`. String → `gridTemplateColumns` value. */
  columns?: number | string;
  /** Gap between cells. Default: `'md'`. */
  gap?: GridGap;
  /** Grow to fill parent flex container (`flex: 1; min-height: 0`). */
  fill?: boolean;
  /** HTML element to render. Default: `'div'`. */
  as?: ElementType;
  children?: ReactNode;
}

export function Grid({
  columns,
  gap = 'md',
  fill = false,
  as = 'div',
  className,
  style,
  children,
  ...rest
}: GridProps) {
  const columnStyle: CSSProperties =
    columns === undefined
      ? {}
      : typeof columns === 'number'
        ? ({ '--grid-cols': columns } as CSSProperties)
        : { gridTemplateColumns: columns };

  return createElement(
    as,
    {
      className: className ? `layout-grid ${className}` : 'layout-grid',
      'data-gap': gap,
      style: {
        ...columnStyle,
        ...(fill ? { flex: 1, minHeight: 0 } : undefined),
        ...style,
      },
      ...rest,
    },
    children,
  );
}

export interface CellProps extends HTMLAttributes<HTMLElement> {
  /** Column span. Number → `span N`. `'full'` → `1 / -1`. */
  span?: number | 'full';
  /** Column start position. */
  start?: number;
  /** Row span. */
  rowSpan?: number;
  /** HTML element to render. Default: `'div'`. */
  as?: ElementType;
  children?: ReactNode;
}

export function Cell({ span, start, rowSpan, as = 'div', style, children, ...rest }: CellProps) {
  const cellStyle: CSSProperties = {
    ...(span !== undefined
      ? { gridColumn: span === 'full' ? '1 / -1' : `span ${span}` }
      : undefined),
    ...(start !== undefined ? { gridColumnStart: start } : undefined),
    ...(rowSpan !== undefined ? { gridRow: `span ${rowSpan}` } : undefined),
    ...style,
  };

  const hasStyles = Object.keys(cellStyle).length > 0;

  return createElement(
    as,
    {
      ...(hasStyles ? { style: cellStyle } : undefined),
      ...rest,
    },
    children,
  );
}
