// packages/ui/src/map-layer.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  DestroyRef,
  effect,
  inject,
  input,
  output,
} from '@angular/core';
import type { GeoJSON } from 'geojson';
import type { MapLayerMouseEvent } from 'maplibre-gl';
import { MapViewComponent } from './map-view.component';
import type {
  MapLayerType,
  MapPaint,
  MapLayout,
  MapFeatureEvent,
} from './map-view.types';

@Component({
  selector: 'ui-map-layer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { 'class': 'map-layer' },
  template: '',
})
export class MapLayerComponent {
  readonly id = input.required<string>();
  readonly type = input.required<MapLayerType>();
  readonly source = input.required<GeoJSON>();
  readonly paint = input<MapPaint>({});
  readonly layout = input<MapLayout>({});
  readonly minZoom = input<number | undefined>(undefined);
  readonly maxZoom = input<number | undefined>(undefined);

  readonly cursor = input<string>('pointer');

  readonly featureClick = output<MapFeatureEvent>();
  readonly featureHover = output<MapFeatureEvent>();

  private readonly parent = inject(MapViewComponent);
  private readonly destroyRef = inject(DestroyRef);
  private registered = false;
  private clickHandler: ((e: MapLayerMouseEvent) => void) | null = null;
  private hoverHandler: ((e: MapLayerMouseEvent) => void) | null = null;
  private enterHandler: (() => void) | null = null;
  private leaveHandler: (() => void) | null = null;

  constructor() {
    effect(() => {
      const map = this.parent.mapInstance();
      if (!map || this.registered) return;
      this.registered = true;
      this.parent.registerLayer(
        this.id(),
        this.source(),
        this.type(),
        this.paint(),
        this.layout(),
        this.minZoom(),
        this.maxZoom(),
      );
      this.wireEvents();
    });

    effect(() => {
      if (!this.registered) return;
      this.parent.updateSource(this.id(), this.source());
    });

    effect(() => {
      const map = this.parent.mapInstance();
      if (!map || !this.registered) return;
      const p = this.paint();
      for (const [key, value] of Object.entries(p)) {
        map.setPaintProperty(this.id(), key, value);
      }
    });

    effect(() => {
      const map = this.parent.mapInstance();
      if (!map || !this.registered) return;
      const l = this.layout();
      for (const [key, value] of Object.entries(l)) {
        map.setLayoutProperty(this.id(), key, value);
      }
    });

    this.destroyRef.onDestroy(() => {
      this.removeEvents();
      if (this.registered) {
        this.parent.unregisterLayer(this.id());
      }
    });
  }

  private wireEvents(): void {
    const map = this.parent.mapInstance();
    if (!map) return;
    const layerId = this.id();

    this.clickHandler = (e: MapLayerMouseEvent) => {
      const feat = e.features?.[0];
      if (!feat) return;
      this.featureClick.emit(this.toFeatureEvent(e, feat));
    };

    this.hoverHandler = (e: MapLayerMouseEvent) => {
      const feat = e.features?.[0];
      if (!feat) return;
      this.featureHover.emit(this.toFeatureEvent(e, feat));
    };

    map.on('click', layerId, this.clickHandler);
    map.on('mousemove', layerId, this.hoverHandler);

    const canvas = map.getCanvas();
    const cursorStyle = this.cursor();
    this.enterHandler = () => { canvas.style.cursor = cursorStyle; };
    this.leaveHandler = () => { canvas.style.cursor = ''; };
    map.on('mouseenter', layerId, this.enterHandler);
    map.on('mouseleave', layerId, this.leaveHandler);
  }

  private removeEvents(): void {
    const map = this.parent.mapInstance();
    if (!map) return;
    const layerId = this.id();
    if (this.clickHandler) map.off('click', layerId, this.clickHandler);
    if (this.hoverHandler) map.off('mousemove', layerId, this.hoverHandler);
    if (this.enterHandler) map.off('mouseenter', layerId, this.enterHandler);
    if (this.leaveHandler) map.off('mouseleave', layerId, this.leaveHandler);
  }

  private toFeatureEvent(
    e: MapLayerMouseEvent,
    feat: { properties?: Record<string, unknown> | null; geometry: GeoJSON.Geometry },
  ): MapFeatureEvent {
    return {
      lngLat: { lng: e.lngLat.lng, lat: e.lngLat.lat },
      feature: {
        properties: feat.properties ?? {},
        geometry: feat.geometry,
      },
    };
  }
}

// packages/react-ui/src/map-layer.tsx
import { useEffect, useRef } from 'react';
import type { AddLayerObject, MapLayerMouseEvent } from 'maplibre-gl';
import type { GeoJSON } from 'geojson';
import type { MapFeatureEvent, MapLayerType, MapLayout, MapPaint } from './map-view.types';
import { useMapView } from './map-view.context';

export interface MapLayerProps {
  id: string;
  type: MapLayerType;
  source: GeoJSON;
  paint?: MapPaint;
  layout?: MapLayout;
  minZoom?: number;
  maxZoom?: number;
  cursor?: string;
  onFeatureClick?: (event: MapFeatureEvent) => void;
  onFeatureHover?: (event: MapFeatureEvent) => void;
}

export function MapLayer({
  id,
  type,
  source,
  paint = {},
  layout = {},
  minZoom,
  maxZoom,
  cursor = 'pointer',
  onFeatureClick,
  onFeatureHover,
}: MapLayerProps) {
  const { map } = useMapView();
  const registeredRef = useRef(false);
  const onClickRef = useRef(onFeatureClick);
  const onHoverRef = useRef(onFeatureHover);
  onClickRef.current = onFeatureClick;
  onHoverRef.current = onFeatureHover;

  useEffect(() => {
    if (!map || registeredRef.current) return;
    registeredRef.current = true;

    map.addSource(id, { type: 'geojson', data: source });
    const layerDef = {
      id,
      type,
      source: id,
      paint,
      layout,
      ...(minZoom != null ? { minzoom: minZoom } : {}),
      ...(maxZoom != null ? { maxzoom: maxZoom } : {}),
    } as unknown as AddLayerObject;
    map.addLayer(layerDef);

    const clickHandler = (e: MapLayerMouseEvent) => {
      const feat = e.features?.[0];
      if (!feat) return;
      onClickRef.current?.({
        lngLat: { lng: e.lngLat.lng, lat: e.lngLat.lat },
        feature: {
          properties: feat.properties ?? {},
          geometry: feat.geometry,
        },
      });
    };

    const hoverHandler = (e: MapLayerMouseEvent) => {
      const feat = e.features?.[0];
      if (!feat) return;
      onHoverRef.current?.({
        lngLat: { lng: e.lngLat.lng, lat: e.lngLat.lat },
        feature: {
          properties: feat.properties ?? {},
          geometry: feat.geometry,
        },
      });
    };

    const canvas = map.getCanvas();
    const enterHandler = () => {
      canvas.style.cursor = cursor;
    };
    const leaveHandler = () => {
      canvas.style.cursor = '';
    };

    map.on('click', id, clickHandler);
    map.on('mousemove', id, hoverHandler);
    map.on('mouseenter', id, enterHandler);
    map.on('mouseleave', id, leaveHandler);

    return () => {
      map.off('click', id, clickHandler);
      map.off('mousemove', id, hoverHandler);
      map.off('mouseenter', id, enterHandler);
      map.off('mouseleave', id, leaveHandler);
      if (map.getLayer(id)) map.removeLayer(id);
      if (map.getSource(id)) map.removeSource(id);
      registeredRef.current = false;
    };
    // Register once when map becomes available
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [map]);

  useEffect(() => {
    if (!map || !registeredRef.current) return;
    const src = map.getSource(id);
    if (src && 'setData' in src) {
      (src as { setData: (d: GeoJSON) => void }).setData(source);
    }
  }, [map, id, source]);

  useEffect(() => {
    if (!map || !registeredRef.current) return;
    for (const [key, value] of Object.entries(paint)) {
      map.setPaintProperty(id, key, value);
    }
  }, [map, id, paint]);

  useEffect(() => {
    if (!map || !registeredRef.current) return;
    for (const [key, value] of Object.entries(layout)) {
      map.setLayoutProperty(id, key, value);
    }
  }, [map, id, layout]);

  return null;
}
