// packages/ui/src/page-header.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'ui-page-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'page-header' },
  template: `
    <div class="page-header-heading">
      <h1 class="page-header-title">{{ title() }}</h1>
      @if (subtitle()) {
        <p class="page-header-subtitle">{{ subtitle() }}</p>
      }
    </div>
    <div class="page-header-actions">
      <ng-content select="[pageHeaderActions]" />
    </div>
  `,
})
export class PageHeaderComponent {
  readonly title = input('');
  readonly subtitle = input('');
}

// packages/react-ui/src/page-header.tsx
import { type ReactNode } from 'react';

export interface PageHeaderProps {
  title?: string;
  subtitle?: string;
  actions?: ReactNode;
}

export function PageHeader({ title, subtitle, actions }: PageHeaderProps) {
  return (
    <div className="page-header">
      <div className="page-header-heading">
        {title && <h1 className="page-header-title">{title}</h1>}
        {subtitle && <p className="page-header-subtitle">{subtitle}</p>}
      </div>
      {actions && <div className="page-header-actions">{actions}</div>}
    </div>
  );
}
