// packages/ui/src/badge.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'ui-badge',
  host: {
    'class': 'badge',
    '[attr.data-variant]': 'variant()',
  },
  template: `<ng-content />`,
})
export class BadgeComponent {
  readonly variant = input<'default' | 'secondary' | 'destructive' | 'outline'>('default');
}

// packages/react-ui-bk/src/badge.tsx
import { type HTMLAttributes, type ReactNode } from 'react';

export type BadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
  children?: ReactNode;
}

export function Badge({
  variant = 'default',
  className,
  children,
  ...props
}: BadgeProps) {
  return (
    <span
      className={className ? `badge ${className}` : 'badge'}
      data-variant={variant}
      {...props}
    >
      {children}
    </span>
  );
}
