// packages/ui/src/card-group.component.ts
import { ChangeDetectionStrategy, Component, input, model } from '@angular/core';

export type CardGroupMode = 'aggregated' | 'disaggregated';

@Component({
  selector: 'ui-card-group',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    'class': 'card-group',
    '[attr.data-mode]': 'mode()',
  },
  template: `
    <button
      type="button"
      class="card-group-toggle"
      (click)="toggle()"
      [attr.aria-expanded]="mode() === 'disaggregated'"
    >
      <span class="card-group-title">{{ title() }}</span>
      <span class="card-group-count">{{ count() }}</span>
      <svg
        class="card-group-chevron"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    </button>
    @if (mode() === 'aggregated') {
      <div class="card-group-summary">
        <ng-content select="[groupSummary]" />
      </div>
    } @else {
      <div class="card-group-items">
        <ng-content />
      </div>
    }
  `,
})
export class CardGroupComponent {
  readonly title = input.required<string>();
  readonly count = input(0);
  readonly mode = model<CardGroupMode>('aggregated');

  toggle(): void {
    this.mode.set(
      this.mode() === 'aggregated' ? 'disaggregated' : 'aggregated',
    );
  }
}

// packages/react-ui-bk/src/card-group.tsx
import { type HTMLAttributes, type ReactNode, useState } from 'react';

export type CardGroupMode = 'aggregated' | 'disaggregated';

export interface CardGroupProps extends HTMLAttributes<HTMLDivElement> {
  title: string;
  count?: number;
  mode?: CardGroupMode;
  onModeChange?: (mode: CardGroupMode) => void;
  summary?: ReactNode;
  children?: ReactNode;
}

export function CardGroup({
  title,
  count = 0,
  mode: controlledMode,
  onModeChange,
  summary,
  className,
  children,
  ...props
}: CardGroupProps) {
  const [internalMode, setInternalMode] = useState<CardGroupMode>('aggregated');
  const mode = controlledMode ?? internalMode;

  function toggle() {
    const next = mode === 'aggregated' ? 'disaggregated' : 'aggregated';
    setInternalMode(next);
    onModeChange?.(next);
  }

  return (
    <div
      className={className ? `card-group ${className}` : 'card-group'}
      data-mode={mode}
      {...props}
    >
      <button
        type="button"
        className="card-group-toggle"
        onClick={toggle}
        aria-expanded={mode === 'disaggregated'}
      >
        <span className="card-group-title">{title}</span>
        <span className="card-group-count">{count}</span>
        <svg
          className="card-group-chevron"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>
      {mode === 'aggregated' ? (
        <div className="card-group-summary">{summary}</div>
      ) : (
        <div className="card-group-items">{children}</div>
      )}
    </div>
  );
}
