// frontend/src/app/shared/ui/form-error.component.ts
import { Component, input } from '@angular/core';
import { AbstractControl } from '@angular/forms';

const ERROR_MESSAGES: Record<string, string> = {
  required: 'This field is required',
  email: 'Please enter a valid email address',
  maxlength: 'Value is too long',
  minlength: 'Value is too short',
};

@Component({
  selector: 'app-form-error',
  template: `
    @if (control() && control()!.invalid && control()!.touched) {
      @for (key of errorKeys(); track key) {
        <p class="text-xs text-destructive mt-xs">{{ getMessage(key) }}</p>
      }
    }
  `,
})
export class FormErrorComponent {
  readonly control = input<AbstractControl | null>(null);

  protected errorKeys(): string[] {
    return Object.keys(this.control()?.errors ?? {});
  }

  protected getMessage(key: string): string {
    return ERROR_MESSAGES[key] ?? key;
  }
}

// packages/react-ui-bk/src/form-error.tsx
const ERROR_MESSAGES: Record<string, string> = {
  required: 'This field is required',
  email: 'Please enter a valid email address',
  maxlength: 'Value is too long',
  minlength: 'Value is too short',
};

export interface FormErrorProps {
  errors?: Record<string, unknown>;
  touched?: boolean;
}

export function FormError({ errors, touched }: FormErrorProps) {
  if (!touched || !errors) return null;
  const keys = Object.keys(errors);
  if (keys.length === 0) return null;

  return (
    <div role="alert">
      {keys.map((key) => (
        <p key={key} className="form-error">
          {ERROR_MESSAGES[key] ?? key}
        </p>
      ))}
    </div>
  );
}
