// apps/main/react-frontend/src/features/dashboard.tsx
import { useMemo } from 'react';
import { Badge, HistogramTimeline, type HistogramBar, type HistogramLabel } from '@aspect/react-ui';

function seededRandom(seed: number) {
  return () => {
    seed = (seed * 16807) % 2147483647;
    return (seed - 1) / 2147483646;
  };
}

function generateBars(count: number, seed: number): HistogramBar[] {
  const rand = seededRandom(seed);
  return Array.from({ length: count }, () => ({
    value: Math.floor(rand() * 100),
  }));
}

function generateLabels(count: number, step: number): HistogramLabel[] {
  return Array.from({ length: Math.ceil(count / step) }, (_, i) => ({
    index: i * step,
    text: `${i * step}`,
  }));
}

interface StatCard { label: string; value: string; change: string; }
interface ActivityItem { message: string; time: string; variant: 'default' | 'secondary' | 'destructive' | 'outline'; }

const stats: StatCard[] = [
  { label: 'Total Users', value: '2,847', change: '+12.5%' },
  { label: 'Active Sessions', value: '423', change: '+3.2%' },
  { label: 'API Calls', value: '1.2M', change: '+8.1%' },
  { label: 'Error Rate', value: '0.03%', change: '-15.4%' },
];

const activity: ActivityItem[] = [
  { message: 'User alice@example.com registered', time: '2 min ago', variant: 'default' },
  { message: 'API rate limit warning triggered', time: '15 min ago', variant: 'destructive' },
  { message: 'Database backup completed', time: '1 hour ago', variant: 'secondary' },
  { message: 'New deployment to staging', time: '3 hours ago', variant: 'outline' },
];

const systemInfo = [
  { label: 'Uptime', value: '99.97%' },
  { label: 'Response Time', value: '142ms' },
  { label: 'Memory Usage', value: '67%' },
  { label: 'CPU Load', value: '23%' },
];

export default function Dashboard() {
  const bars = useMemo(() => generateBars(24, 42), []);
  const labels = useMemo(() => generateLabels(24, 6), []);
  const errorBars = useMemo(() => generateBars(24, 99), []);
  const errorLabels = useMemo(() => generateLabels(24, 6), []);

  return (
    <div className="p-lg flex flex-col gap-lg">
      <div className="flex items-center gap-sm">
        <h1 className="text-2xl font-bold">Dashboard</h1>
        <Badge>Live</Badge>
      </div>
      <div className="grid gap-md" style={{ gridTemplateColumns: 'repeat(4, 1fr)' }}>
        {stats.map((stat) => (
          <div key={stat.label} className="card">
            <p className="text-sm text-muted-foreground">{stat.label}</p>
            <p className="text-2xl font-bold">{stat.value}</p>
            <p className={`text-sm ${stat.change.startsWith('+') ? 'text-success' : 'text-destructive'}`}>{stat.change}</p>
          </div>
        ))}
      </div>
      <div className="grid gap-md" style={{ gridTemplateColumns: '2fr 1fr' }}>
        <div className="card">
          <h2 className="card-title">Request Volume (24h)</h2>
          <HistogramTimeline bars={bars} labels={labels} ariaLabel="Request volume over 24 hours" />
        </div>
        <div className="card">
          <h2 className="card-title">Recent Activity</h2>
          <div className="flex flex-col gap-sm">
            {activity.map((item, i) => (
              <div key={i} className="flex items-center justify-between gap-sm">
                <span className="text-sm">{item.message}</span>
                <Badge variant={item.variant}>{item.time}</Badge>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="grid gap-md" style={{ gridTemplateColumns: '2fr 1fr' }}>
        <div className="card">
          <h2 className="card-title">Error Rate (24h)</h2>
          <HistogramTimeline bars={errorBars} labels={errorLabels} ariaLabel="Error rate over 24 hours" variant="destructive" />
        </div>
        <div className="card">
          <h2 className="card-title">System</h2>
          <div className="flex flex-col gap-sm">
            {systemInfo.map((info) => (
              <div key={info.label} className="flex justify-between">
                <span className="text-sm text-muted-foreground">{info.label}</span>
                <span className="text-sm font-bold">{info.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, signal } from '@angular/core';
import { BadgeComponent, HistogramTimelineComponent, type HistogramBar, type HistogramLabel } from '@aspect/ui';

function seededRandom(seed: number) {
  return () => {
    seed = (seed * 16807) % 2147483647;
    return (seed - 1) / 2147483646;
  };
}

function generateBars(count: number, max: number, seed: number): HistogramBar[] {
  const rand = seededRandom(seed);
  return Array.from({ length: count }, () => ({ value: Math.floor(rand() * max) }));
}

function generateLabels(count: number, interval: number, formatter: (i: number) => string): HistogramLabel[] {
  const labels: HistogramLabel[] = [];
  for (let i = 0; i < count; i += interval) {
    labels.push({ index: i, text: formatter(i) });
  }
  return labels;
}

interface StatCard {
  label: string;
  value: string;
  change: string;
  up: boolean;
}

interface ActivityItem {
  action: string;
  target: string;
  time: string;
  badge: 'default' | 'secondary' | 'destructive' | 'outline';
  badgeLabel: string;
}

@Component({
  selector: 'app-dashboard',
  imports: [HistogramTimelineComponent, BadgeComponent],
  template: `
    <div class="flex flex-col gap-xl px-lg py-lg mx-auto" style="max-width: 72rem">

      <!-- Header -->
      <div class="flex flex-row items-center justify-between">
        <div>
          <h1 class="text-2xl font-bold text-foreground">Dashboard</h1>
          <p class="text-sm text-muted-foreground mt-xs">Monday, March 11 2026</p>
        </div>
        <app-badge variant="outline">Live</app-badge>
      </div>

      <!-- Stat cards row -->
      <div class="grid grid-cols-4 gap-md">
        @for (stat of stats; track stat.label) {
          <div class="card">
            <p class="text-xs text-muted-foreground uppercase tracking-wide font-medium">{{ stat.label }}</p>
            <p class="text-2xl font-bold text-foreground mt-xs">{{ stat.value }}</p>
            <p class="text-xs mt-xs" [class]="stat.up ? 'text-xs mt-xs text-primary' : 'text-xs mt-xs text-destructive'">
              {{ stat.change }}
            </p>
          </div>
        }
      </div>

      <!-- Main content: histogram + activity feed -->
      <div class="grid grid-cols-3 gap-md">

        <!-- Histogram card (2/3 width) -->
        <div class="card col-span-2">
          <div class="flex flex-row items-center justify-between mb-md">
            <h2 class="card-title" style="margin-block-end: 0">Events per minute</h2>
            <span class="font-mono text-xs text-muted-foreground border px-sm py-xs rounded-sm">12h window</span>
          </div>
          <app-histogram-timeline
            [bars]="bars()"
            [labels]="labels()"
            [ariaLabel]="'Events per minute, last 12 hours'"
          />
        </div>

        <!-- Activity feed (1/3 width) -->
        <div class="card flex flex-col">
          <h2 class="card-title">Recent activity</h2>
          <div class="flex flex-col gap-sm flex-1">
            @for (item of activity; track item.time) {
              <div class="flex flex-col gap-xs py-sm" style="border-bottom: 1px solid var(--color-border)">
                <div class="flex flex-row items-center justify-between">
                  <span class="text-sm text-foreground font-medium">{{ item.action }}</span>
                  <app-badge [variant]="item.badge">{{ item.badgeLabel }}</app-badge>
                </div>
                <p class="text-xs text-muted-foreground">{{ item.target }}</p>
                <p class="text-xs text-muted-foreground" style="opacity: 0.6">{{ item.time }}</p>
              </div>
            }
          </div>
        </div>
      </div>

      <!-- Bottom row: error histogram + system info -->
      <div class="grid grid-cols-3 gap-md">

        <!-- Error rate histogram -->
        <div class="card col-span-2">
          <div class="flex flex-row items-center justify-between mb-md">
            <h2 class="card-title" style="margin-block-end: 0">Error rate</h2>
            <app-badge variant="destructive">3 spikes</app-badge>
          </div>
          <app-histogram-timeline
            [bars]="errorBars()"
            [labels]="errorLabels()"
            [ariaLabel]="'Errors per hour, last 24 hours'"
            variant="destructive"
          />
        </div>

        <!-- System status -->
        <div class="card flex flex-col gap-md">
          <h2 class="card-title">System</h2>
          @for (item of systemInfo; track item.label) {
            <div class="flex flex-row items-center justify-between">
              <span class="text-sm text-muted-foreground">{{ item.label }}</span>
              <span class="font-mono text-sm text-foreground">{{ item.value }}</span>
            </div>
          }
          <div style="border-top: 1px solid var(--color-border)" class="py-sm mt-sm">
            <div class="flex flex-row items-center gap-sm">
              <span class="rounded-full bg-primary" style="width: 0.5rem; height: 0.5rem"></span>
              <span class="text-xs text-muted-foreground">All systems operational</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class DashboardComponent {
  protected readonly bars = signal(generateBars(720, 50, 42));
  protected readonly labels = signal(
    generateLabels(720, 60, i => {
      const hour = 8 + Math.floor(i / 60);
      return `${String(hour)}:${String(i % 60).padStart(2, '0')}`;
    }),
  );

  protected readonly errorBars = signal(generateBars(24, 15, 99));
  protected readonly errorLabels = signal(
    generateLabels(24, 4, i => `${String(i)}:00`),
  );

  protected readonly stats: StatCard[] = [
    { label: 'Total events', value: '14,892', change: '+12.3% vs yesterday', up: true },
    { label: 'Avg latency', value: '42ms', change: '-8.1% vs yesterday', up: true },
    { label: 'Error rate', value: '0.24%', change: '+0.03% vs yesterday', up: false },
    { label: 'Active users', value: '1,247', change: '+5.7% vs yesterday', up: true },
  ];

  protected readonly activity: ActivityItem[] = [
    { action: 'Deployment', target: 'frontend v2.4.1 → production', time: '2 min ago', badge: 'default', badgeLabel: 'deploy' },
    { action: 'Alert resolved', target: 'CPU spike on worker-03', time: '18 min ago', badge: 'secondary', badgeLabel: 'resolved' },
    { action: 'Error spike', target: '429 rate-limit on /api/search', time: '1h ago', badge: 'destructive', badgeLabel: 'error' },
    { action: 'Config change', target: 'Feature flag dark-mode enabled', time: '3h ago', badge: 'outline', badgeLabel: 'config' },
    { action: 'Deployment', target: 'backend v1.8.0 → staging', time: '5h ago', badge: 'default', badgeLabel: 'deploy' },
  ];

  protected readonly systemInfo = [
    { label: 'Uptime', value: '14d 7h 32m' },
    { label: 'CPU', value: '23%' },
    { label: 'Memory', value: '4.2 / 8 GB' },
    { label: 'Disk', value: '67% used' },
    { label: 'DB connections', value: '42 / 100' },
  ];
}
